---
- name: Install requirements
  package:
    name: ["git"]
    state: present

- name: Check if GRR directories already exists
  stat:
    path: "{{ grr_separate_git_dir }}"
  register: grr_git_dir

- name: Clone GRR git repository
  git:
    repo: "{{ grr_git_repo_url }}"
    dest: "{{ grr_content_dest }}"
    version: "{{ grr_git_branch_version }}"
    separate_git_dir: "{{ grr_separate_git_dir }}"
    force: true
  when: not grr_git_dir.stat.exists or grr_force_update

- name: Copy Configuration File
  template:
    src: connect.inc.php.j2
    dest: "{{ grr_content_dest }}/include/connect.inc.php"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true

# - name: Deploy tables.my.sql (UTF8)
#  template:
#    src: tables.my.sql.j2
#    dest: "{{ grr_content_dest }}/installation/tables.my.sql"
#    owner: www-data
#    group: www-data
#    mode: "0640"
#    force: true

- name: Deploy LDAP configuration
  template:
    src: config_ldap.inc.php.ori.j2
    dest: "{{ grr_content_dest }}/include/config_ldap.inc.php.ori"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true
  when: grr_use_ldap

- name: Change GRR directory owner
  file:
    path: "{{ grr_content_dest }}"
    owner: "www-data"
    group: "www-data"
    recurse: true
