---
- name: Install requirements
  ansible.builtin.package:
    name: ["git"]
    state: present

- name: Check if GRR directories already exists
  stat:
    path: "{{ grr_separate_git_dir }}"
  register: grr_git_dir

- name: Add execption for git repository ownership
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ grr_content_dest }}"
  when: grr_force_update

- name: Clone GRR git repository
  ansible.builtin.git:
    repo: "{{ grr_git_repo_url }}"
    dest: "{{ grr_content_dest }}"
    version: "{{ grr_git_branch_version }}"
    separate_git_dir: "{{ grr_separate_git_dir }}"
    force: true
  when: not grr_git_dir.stat.exists or grr_force_update

- block:
    - name: Copy Connect File
      template:
        src: connect.inc.php.j2
        dest: "{{ grr_content_dest }}/include/connect.inc.php"
        owner: www-data
        group: www-data
        mode: "0640"
        force: true
      when: grr_force_update

    - name: Copy Configuration File
      template:
        src: config.inc.php.j2
        dest: "{{ grr_content_dest }}/include/config.inc.php"
        owner: www-data
        group: www-data
        mode: "0640"
        force: true

    - name: Deploy LDAP configuration
      template:
        src: config_ldap.inc.php.j2
        dest: "{{ grr_content_dest }}/include/config_ldap.inc.php"
        owner: www-data
        group: www-data
        mode: "0640"
        force: true
      when: grr_use_ldap
  when: grr_git_branch_version == "v3.5.1"

- block:
    - name: Copy Connect File
      template:
        src: connect.inc.php.j2
        dest: "{{ grr_content_dest }}/personnalisation/connect.inc.php"
        owner: www-data
        group: www-data
        mode: "0640"
        force: true
      when: grr_force_update

    - name: Copy Configuration File
      template:
        src: config.inc.php.j2
        dest: "{{ grr_content_dest }}/personnalisation/configperso.inc.php"
        owner: www-data
        group: www-data
        mode: "0640"
        force: true

    - name: Deploy LDAP configuration
      template:
        src: config_ldap.inc.php.j2
        dest: "{{ grr_content_dest }}/personnalisation/config_ldap.inc.php"
        owner: www-data
        group: www-data
        mode: "0640"
        force: true
      when: grr_use_ldap
  when: grr_git_branch_version == "v4.1.1"

- name: Change GRR directory owner
  file:
    path: "{{ grr_content_dest }}"
    owner: "www-data"
    group: "www-data"
    recurse: true
