---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: supertarto.apache
    - role: supertarto.mariadb
    - role: supertarto.php
    - role: supertarto.grr
  vars:
    php_packages:
      - php7.3
      - php7.3-common
      - php7.3-mysql
      - php7.3-gd
      - php7.3-mbstring
      - php7.3-curl
      - php7.3-json
      - php7.3-ldap
      - php7.3-pdo
      - php7.3-xml
    apache_create_vhosts: true
    apache_vhosts_filename: "grr.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        documentroot: "{{ grr_content_dest }}"
        serveradmin: admin@localhost
        custom_param: |
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
          LogLevel warn
        directory:
          - path: "{{ grr_content_dest }}"
            config: |
              AllowOverride All
              Order deny,allow
              allow from all

    mariadb_use_dump_script: false
    mariadb_databases:
      - name: "GRRBase"

    mariadb_users:
      - name: "{{ grr_db_user_name }}"
        host: "localhost"
        password: "{{ grr_db_password }}"
        priv: "{{ grr_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"

    grr_db_name: "GRRBase"
    grr_db_user_name: "grruser"
    grr_db_password: "grrpassword"
    grr_db_apikey: "mypassphrase"
